#Requires -Version 5.1
<#
.SYNOPSIS
    windows-wsl-optimizer の初期セットアップを行う
.DESCRIPTION
    以下を実行します:
      1. .wslconfig の自動生成・調整 (WSL2メモリ上限設定)
      2. 環境変数 SLACK_BOT_TOKEN / SLACK_CHANNEL の保存
.EXAMPLE
    .\setup.ps1
    .\setup.ps1 -WslMemoryGB 8 -SlackToken "xoxb-..." -SlackChannel "#general"
#>

[CmdletBinding()]
param(
    # WSL2 に割り当てるメモリ上限 (GB)。0 で自動計算 (物理メモリの50%)
    [int]$WslMemoryGB = 0,
    # WSL2 に割り当てる CPU コア数。0 で自動計算 (論理コアの50%)
    [int]$WslProcessors = 0,
    # Slack Bot Token (xoxb-...) （省略可）
    [string]$SlackToken,
    # Slack 投稿先チャンネル (#general など) （省略可）
    [string]$SlackChannel,
    # .wslconfig 生成をスキップ
    [switch]$SkipWslConfig,
    # 現在の設定状態を表示して終了
    [switch]$Status
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Continue"

Write-Host ("=" * 60)
Write-Host "  Windows Memory Optimizer - Setup"
Write-Host ("=" * 60)

# ---- Status モード ----
if ($Status) {
    Write-Host "`n[.wslconfig]" -ForegroundColor Cyan
    $wslConfigPath = "$env:USERPROFILE\.wslconfig"
    if (Test-Path $wslConfigPath) {
        Write-Host "  パス: $wslConfigPath" -ForegroundColor Green
        Get-Content $wslConfigPath | ForEach-Object { Write-Host "  $_" }
    } else {
        Write-Host "  未作成" -ForegroundColor Yellow
    }

    Write-Host "`n[Slack 環境変数]" -ForegroundColor Cyan
    $token   = [System.Environment]::GetEnvironmentVariable("SLACK_BOT_TOKEN", "User")
    $channel = [System.Environment]::GetEnvironmentVariable("SLACK_CHANNEL", "User")
    if ($token) {
        $masked = $token.Substring(0, [math]::Min(10, $token.Length)) + "..."
        Write-Host "  SLACK_BOT_TOKEN : $masked" -ForegroundColor Green
    } else {
        Write-Host "  SLACK_BOT_TOKEN : 未設定" -ForegroundColor Yellow
    }
    if ($channel) {
        Write-Host "  SLACK_CHANNEL   : $channel" -ForegroundColor Green
    } else {
        Write-Host "  SLACK_CHANNEL   : 未設定" -ForegroundColor Yellow
    }

    Write-Host ""
    return
}

# ---- 1. .wslconfig 生成・調整 ----
if (-not $SkipWslConfig) {
    Write-Host "`n[1/2] .wslconfig を設定します" -ForegroundColor Cyan

    $wslConfigPath = "$env:USERPROFILE\.wslconfig"
    $os      = Get-CimInstance Win32_OperatingSystem
    $cs      = Get-CimInstance Win32_ComputerSystem
    $physGB  = [math]::Round($os.TotalVisibleMemorySize / 1MB, 0)
    $physCPU = $cs.NumberOfLogicalProcessors

    $memGB = if ($WslMemoryGB  -gt 0) { $WslMemoryGB  } else { [math]::Max(2, [math]::Floor($physGB  / 2)) }
    $cpuN  = if ($WslProcessors -gt 0) { $WslProcessors } else { [math]::Max(1, [math]::Floor($physCPU / 2)) }

    if ($memGB -gt $physGB) {
        $memGB = [math]::Floor($physGB * 0.8)
        Write-Warning "WslMemoryGB が物理メモリを超えているため $memGB GB に調整しました"
    }

    $config = @"
# Generated by windows-wsl-optimizer setup.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
# https://github.com/9en/windows-wsl-optimizer
[wsl2]
# WSL2 に割り当てる最大メモリ (物理メモリ: $physGB GB の約50%)
memory=$($memGB)GB

# WSL2 に割り当てる最大CPUコア数 (論理コア: $physCPU の約50%)
processors=$cpuN

# スワップファイルサイズ (メモリの25%)
swap=$([math]::Max(1, [math]::Floor($memGB / 4)))GB

# WSL2 が使用するメモリを Windows に返す (メモリ解放効果あり)
pageReporting=true

# ローカルホスト転送
localhostForwarding=true
"@

    if (Test-Path $wslConfigPath) {
        $backup = "$wslConfigPath.bak_$(Get-Date -Format 'yyyyMMddHHmmss')"
        Copy-Item $wslConfigPath $backup
        Write-Host "   既存の .wslconfig をバックアップしました: $backup" -ForegroundColor Yellow
    }

    Set-Content -Path $wslConfigPath -Value $config -Encoding UTF8
    Write-Host "   .wslconfig を生成しました: $wslConfigPath" -ForegroundColor Green
    Write-Host "   WSL2 メモリ上限: $memGB GB / CPU: $cpuN コア" -ForegroundColor Green
    Write-Host "   ※ 反映するには WSL2 を再起動してください: wsl --shutdown" -ForegroundColor Yellow
}

# ---- 2. Slack 設定 ----
Write-Host "`n[2/2] Slack 通知設定" -ForegroundColor Cyan

if ($SlackToken) {
    [System.Environment]::SetEnvironmentVariable("SLACK_BOT_TOKEN", $SlackToken, "User")
    Write-Host "   SLACK_BOT_TOKEN を設定しました (ユーザースコープ)" -ForegroundColor Green
} elseif ([System.Environment]::GetEnvironmentVariable("SLACK_BOT_TOKEN", "User")) {
    Write-Host "   SLACK_BOT_TOKEN は設定済みです" -ForegroundColor Green
} else {
    Write-Host "   SLACK_BOT_TOKEN が未設定です" -ForegroundColor Yellow
    Write-Host '   後から設定: [System.Environment]::SetEnvironmentVariable("SLACK_BOT_TOKEN", "xoxb-...", "User")' -ForegroundColor White
}

if ($SlackChannel) {
    [System.Environment]::SetEnvironmentVariable("SLACK_CHANNEL", $SlackChannel, "User")
    Write-Host "   SLACK_CHANNEL を設定しました: $SlackChannel (ユーザースコープ)" -ForegroundColor Green
} elseif ([System.Environment]::GetEnvironmentVariable("SLACK_CHANNEL", "User")) {
    Write-Host "   SLACK_CHANNEL は設定済みです: $([System.Environment]::GetEnvironmentVariable('SLACK_CHANNEL', 'User'))" -ForegroundColor Green
} else {
    Write-Host "   SLACK_CHANNEL が未設定です" -ForegroundColor Yellow
    Write-Host '   後から設定: [System.Environment]::SetEnvironmentVariable("SLACK_CHANNEL", "#general", "User")' -ForegroundColor White
}

# ---- 既存のスケジュールタスクを削除 ----
$existingTask = Get-ScheduledTask -TaskName "MemoryOptimizer" -ErrorAction SilentlyContinue
if ($existingTask) {
    Unregister-ScheduledTask -TaskName "MemoryOptimizer" -Confirm:$false -ErrorAction SilentlyContinue
    Write-Host "`n[情報] 既存のタスクスケジューラ登録 (MemoryOptimizer) を削除しました" -ForegroundColor Yellow
}

# ---- 完了 ----
Write-Host ""
Write-Host ("=" * 60)
Write-Host "  セットアップ完了！" -ForegroundColor Green
Write-Host ("=" * 60)
Write-Host @"

次のステップ:
  1. WSL2 を再起動して .wslconfig を反映する
       wsl --shutdown

  2. メモリレポートを確認する
       .\report.ps1

  3. 通知テスト
       .\notify.ps1 -Message "テスト通知"

手動クリーンアップの実行方法:
  # 基本（クリーンアップ + レポート + Slack通知）
  .\cleanup.ps1 -Report -Notify

  # WSL2を停止せずに実行（WSL作業中に推奨）
  .\cleanup.ps1 -SkipWsl -Report -Notify

  # 事前確認（実際には何も変更しない）
  .\cleanup.ps1 -DryRun

  # Docker削除もスキップ
  .\cleanup.ps1 -SkipDocker -SkipWsl -Report -Notify

"@
