#Requires -Version 5.1
<#
.SYNOPSIS
    windows-memory-optimizer の初期セットアップを行う
.DESCRIPTION
    以下を実行します:
      1. .wslconfig の自動生成・調整 (WSL2メモリ上限設定)
      2. タスクスケジューラへの定期実行登録 (report + cleanup)
      3. 環境変数 SLACK_BOT_TOKEN / SLACK_CHANNEL の保存
.EXAMPLE
    # 管理者権限のPowerShellで実行してください
    .\setup.ps1
    .\setup.ps1 -WslMemoryGB 8 -SlackToken "xoxb-..." -SlackChannel "#general"
#>

[CmdletBinding()]
param(
    # WSL2 に割り当てるメモリ上限 (GB)。0 で自動計算 (物理メモリの50%)
    [int]$WslMemoryGB = 0,
    # WSL2 に割り当てる CPU コア数。0 で自動計算 (論理コアの50%)
    [int]$WslProcessors = 0,
    # Slack Bot Token (xoxb-...) （省略可）
    [string]$SlackToken,
    # Slack 投稿先チャンネル (#general など) （省略可）
    [string]$SlackChannel,
    # タスクスケジューラ: report を実行する時刻 (HH:mm)
    # タスクスケジューラ: 実行時刻 (HH:mm)
    [string]$ScheduleTime = "20:00",
    # タスクスケジューラ登録をスキップ
    [switch]$SkipScheduler,
    # .wslconfig 生成をスキップ
    [switch]$SkipWslConfig,
    # 現在の設定状態を表示して終了
    [switch]$Status
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Continue"

$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
    [Security.Principal.WindowsBuiltInRole]::Administrator
)
if (-not $isAdmin) {
    Write-Warning "管理者権限で実行することを推奨します（タスクスケジューラ登録に必要です）"
}

Write-Host ("=" * 60)
Write-Host "  Windows Memory Optimizer - Setup"
Write-Host ("=" * 60)

# ---- Status モード ----
if ($Status) {
    Write-Host "`n[.wslconfig]" -ForegroundColor Cyan
    $wslConfigPath = "$env:USERPROFILE\.wslconfig"
    if (Test-Path $wslConfigPath) {
        Write-Host "  パス: $wslConfigPath" -ForegroundColor Green
        Get-Content $wslConfigPath | ForEach-Object { Write-Host "  $_" }
    } else {
        Write-Host "  未作成" -ForegroundColor Yellow
    }

    Write-Host "`n[Slack 環境変数]" -ForegroundColor Cyan
    $token   = [System.Environment]::GetEnvironmentVariable("SLACK_BOT_TOKEN", "User")
    $channel = [System.Environment]::GetEnvironmentVariable("SLACK_CHANNEL", "User")
    if ($token) {
        $masked = $token.Substring(0, [math]::Min(10, $token.Length)) + "..."
        Write-Host "  SLACK_BOT_TOKEN : $masked" -ForegroundColor Green
    } else {
        Write-Host "  SLACK_BOT_TOKEN : 未設定" -ForegroundColor Yellow
    }
    if ($channel) {
        Write-Host "  SLACK_CHANNEL   : $channel" -ForegroundColor Green
    } else {
        Write-Host "  SLACK_CHANNEL   : 未設定" -ForegroundColor Yellow
    }

    Write-Host "`n[タスクスケジューラ]" -ForegroundColor Cyan
    $task = Get-ScheduledTask -TaskName "MemoryOptimizer" -ErrorAction SilentlyContinue
    if ($task) {
        $info = $task | Get-ScheduledTaskInfo -ErrorAction SilentlyContinue
        Write-Host "  状態           : $($task.State)" -ForegroundColor Green
        Write-Host "  トリガー       : $($task.Triggers[0].StartBoundary)" -ForegroundColor Green
        Write-Host "  実行コマンド   : $($task.Actions[0].Arguments)" -ForegroundColor Green
        if ($info.LastRunTime -and $info.LastRunTime -ne [datetime]::MinValue) {
            Write-Host "  前回実行       : $($info.LastRunTime)" -ForegroundColor Green
            Write-Host "  前回結果       : $($info.LastTaskResult)" -ForegroundColor Green
        } else {
            Write-Host "  前回実行       : まだ実行されていません" -ForegroundColor Yellow
        }
    } else {
        Write-Host "  未登録" -ForegroundColor Yellow
    }

    Write-Host ""
    return
}

# ---- 1. .wslconfig 生成・調整 ----
if (-not $SkipWslConfig) {
    Write-Host "`n[1/3] .wslconfig を設定します" -ForegroundColor Cyan

    $wslConfigPath = "$env:USERPROFILE\.wslconfig"
    $os      = Get-CimInstance Win32_OperatingSystem
    $cs      = Get-CimInstance Win32_ComputerSystem
    $physGB  = [math]::Round($os.TotalVisibleMemorySize / 1MB, 0)
    $physCPU = $cs.NumberOfLogicalProcessors

    $memGB = if ($WslMemoryGB  -gt 0) { $WslMemoryGB  } else { [math]::Max(2, [math]::Floor($physGB  / 2)) }
    $cpuN  = if ($WslProcessors -gt 0) { $WslProcessors } else { [math]::Max(1, [math]::Floor($physCPU / 2)) }

    if ($memGB -gt $physGB) {
        $memGB = [math]::Floor($physGB * 0.8)
        Write-Warning "WslMemoryGB が物理メモリを超えているため $memGB GB に調整しました"
    }

    $config = @"
# Generated by windows-memory-optimizer setup.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
# https://github.com/9en/windows-memory-optimizer
[wsl2]
# WSL2 に割り当てる最大メモリ (物理メモリ: $physGB GB の約50%)
memory=$($memGB)GB

# WSL2 に割り当てる最大CPUコア数 (論理コア: $physCPU の約50%)
processors=$cpuN

# スワップファイルサイズ (メモリの25%)
swap=$([math]::Max(1, [math]::Floor($memGB / 4)))GB

# WSL2 が使用するメモリを Windows に返す (メモリ解放効果あり)
pageReporting=true

# ローカルホスト転送
localhostForwarding=true
"@

    if (Test-Path $wslConfigPath) {
        $backup = "$wslConfigPath.bak_$(Get-Date -Format 'yyyyMMddHHmmss')"
        Copy-Item $wslConfigPath $backup
        Write-Host "   既存の .wslconfig をバックアップしました: $backup" -ForegroundColor Yellow
    }

    Set-Content -Path $wslConfigPath -Value $config -Encoding UTF8
    Write-Host "   .wslconfig を生成しました: $wslConfigPath" -ForegroundColor Green
    Write-Host "   WSL2 メモリ上限: $memGB GB / CPU: $cpuN コア" -ForegroundColor Green
    Write-Host "   ※ 反映するには WSL2 を再起動してください: wsl --shutdown" -ForegroundColor Yellow
}

# ---- 2. Slack 設定 ----
Write-Host "`n[2/3] Slack 通知設定" -ForegroundColor Cyan

if ($SlackToken) {
    [System.Environment]::SetEnvironmentVariable("SLACK_BOT_TOKEN", $SlackToken, "User")
    Write-Host "   SLACK_BOT_TOKEN を設定しました (ユーザースコープ)" -ForegroundColor Green
} elseif ([System.Environment]::GetEnvironmentVariable("SLACK_BOT_TOKEN", "User")) {
    Write-Host "   SLACK_BOT_TOKEN は設定済みです" -ForegroundColor Green
} else {
    Write-Host "   SLACK_BOT_TOKEN が未設定です" -ForegroundColor Yellow
    Write-Host '   後から設定: [System.Environment]::SetEnvironmentVariable("SLACK_BOT_TOKEN", "xoxb-...", "User")' -ForegroundColor White
}

if ($SlackChannel) {
    [System.Environment]::SetEnvironmentVariable("SLACK_CHANNEL", $SlackChannel, "User")
    Write-Host "   SLACK_CHANNEL を設定しました: $SlackChannel (ユーザースコープ)" -ForegroundColor Green
} elseif ([System.Environment]::GetEnvironmentVariable("SLACK_CHANNEL", "User")) {
    Write-Host "   SLACK_CHANNEL は設定済みです: $([System.Environment]::GetEnvironmentVariable('SLACK_CHANNEL', 'User'))" -ForegroundColor Green
} else {
    Write-Host "   SLACK_CHANNEL が未設定です" -ForegroundColor Yellow
    Write-Host '   後から設定: [System.Environment]::SetEnvironmentVariable("SLACK_CHANNEL", "#general", "User")' -ForegroundColor White
}

# ---- 3. タスクスケジューラ登録 ----
if (-not $SkipScheduler) {
    Write-Host "`n[3/3] タスクスケジューラに定期実行を登録します" -ForegroundColor Cyan

    if (-not $isAdmin) {
        Write-Warning "タスクスケジューラ登録には管理者権限が必要です。スキップします。"
        Write-Host "   管理者権限で再実行するか -SkipScheduler を指定してください。" -ForegroundColor Yellow
    } else {
        $pwshCmd = Get-Command pwsh       -ErrorAction SilentlyContinue
        $ps5Cmd  = Get-Command powershell -ErrorAction SilentlyContinue
        $pwsh = if ($pwshCmd) { $pwshCmd.Source } elseif ($ps5Cmd) { $ps5Cmd.Source } else { "powershell.exe" }

        # 旧タスクがあれば削除
        foreach ($old in @("MemoryOptimizer-Report", "MemoryOptimizer-Cleanup")) {
            Unregister-ScheduledTask -TaskName $old -Confirm:$false -ErrorAction SilentlyContinue
        }

        $taskName = "MemoryOptimizer"
        try {
            Register-ScheduledTask `
                -TaskName    $taskName `
                -Action      (New-ScheduledTaskAction -Execute $pwsh -Argument "-NonInteractive -NoProfile -ExecutionPolicy Bypass -File `"$PSScriptRoot\cleanup.ps1`" -Report -Notify") `
                -Trigger     (New-ScheduledTaskTrigger -Daily -At $ScheduleTime) `
                -Settings    (New-ScheduledTaskSettingsSet -ExecutionTimeLimit (New-TimeSpan -Hours 1) -MultipleInstances IgnoreNew -StartWhenAvailable) `
                -Description "windows-memory-optimizer: 毎日 $ScheduleTime にクリーンアップ→レポート生成・通知" `
                -RunLevel    Highest | Out-Null
            Write-Host "   [$taskName] 毎日 $ScheduleTime に登録しました（クリーンアップ→レポート→通知）" -ForegroundColor Green
        } catch {
            Write-Host "   [$taskName] 登録失敗: $_" -ForegroundColor Red
        }
    }
}

# ---- 完了 ----
Write-Host ""
Write-Host ("=" * 60)
Write-Host "  セットアップ完了！" -ForegroundColor Green
Write-Host ("=" * 60)
Write-Host @"

次のステップ:
  1. WSL2 を再起動して .wslconfig を反映する
       wsl --shutdown

  2. メモリレポートを今すぐ確認する
       .\report.ps1

  3. クリーンアップを今すぐ実行する
       .\cleanup.ps1

  4. 通知テスト
       .\notify.ps1 -Message "テスト通知"

"@
